version = 1

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "react",
    "vue"
  ]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/volkovsd1/laketest"